'use strict';
module.exports = {
	bowerJson: require('./component-boilerplate/bower-json'),
	ciConfigYml: require('./component-boilerplate/ci-config-yml'),
	demoJs: require('./component-boilerplate/demo-js'),
	demoMustache: require('./component-boilerplate/demo-mustache'),
	demoPa11y: require('./component-boilerplate/demo-pa11y'),
	demoSass: require('./component-boilerplate/demo-sass'),
	eslint: require('./component-boilerplate/eslint'),
	gitIgnore: require('./component-boilerplate/git-ignore'),
	mainJs: require('./component-boilerplate/main-js'),
	mainScss: require('./component-boilerplate/main-scss'),
	migration: require('./component-boilerplate/migration'),
	origamiJson: require('./component-boilerplate/origami-json'),
	readMe: require('./component-boilerplate/read-me'),
	srcJs: require('./component-boilerplate/src-js'),
	srcSassMixins: require('./component-boilerplate/src-sass-mixins'),
	srcSassVariables: require('./component-boilerplate/src-sass-variables'),
	srcSassBrand: require('./component-boilerplate/src-sass-brand'),
	packageJson: require('./component-boilerplate/package-json'),
	testFixtures: require('./component-boilerplate/test-fixtures'),
	testMain: require('./component-boilerplate/test-main'),
	testSassMain: require('./component-boilerplate/test-sass-main'),
	testSassMixins: require('./component-boilerplate/test-sass-mixins')
};
